# Generated by Django 5.1.4 on 2025-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tips_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('anime', models.CharField(max_length=100)),
                ('genere', models.CharField(max_length=2)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
