# Generated by Django 5.1.4 on 2025-05-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tips_table',
            new_name='anime_list',
        ),
    ]
