# Generated by Django 5.1.4 on 2025-05-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_tips_table_anime_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime_list',
            name='slno',
        ),
    ]
