# Generated by Django 5.1.4 on 2025-05-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_anime_list_slno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anime_list',
            new_name='Anime',
        ),
    ]
