# Generated by Django 5.1.4 on 2025-06-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_anime_list_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='emotion_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
