# Generated by Django 5.1.4 on 2025-06-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_login_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_table',
            new_name='LoginTable',
        ),
    ]
